import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../../components/navbar';
import Footer from '../../components/footer';

export default function posts( { publicPosts }:any ) {
    return (
            <>
                <Head>
                    <title>Blog List</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="flex flex-col">
                    <Navbar />
                </div>
                <div className="dark:bg-gray-900">
                    <div className="mx-auto max-w-3xl px-4 sm:px-6 xl:max-w-5xl xl:px-0 dark:bg-gray-900">
                        <div className="flex flex-col justify-between">
                            <main className="mb-auto">
                                <div className="divide-y divide-gray-200 dark:divide-gray-700">
                                    <div className="space-y-2 pt-6 pb-8 md:space-y-5">
                                        <h1 className="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:text-6xl md:leading-14">Latest</h1>
                                        <p className="text-lg leading-7 text-gray-500 dark:text-gray-400">What&quot;s been going on recently.</p>
                                    </div>
                                    <ul className="divide-y divide-gray-200 dark:divide-gray-700">
                                        { publicPosts.length ? (
                                            publicPosts.map( (post:any, index:number) => (
                                                <li className="py-12" key={index}>
                                                    <article>
                                                        <div className="space-y-2 xl:grid xl:grid-cols-4 xl:items-baseline xl:space-y-0">
                                                            <dl>
                                                                <dt className="sr-only">Published on</dt>
                                                                <dd className="text-base font-medium leading-6 text-gray-500 dark:text-gray-400">
                                                                    
                                                                    <Image width={400} height={200} src={post.bannerImage} alt="" className="object-cover w-full rounded h-96 md:h-auto md:w-48 md:rounded-none md:rounded" />
                                                                    
                                                                    {/* <time datetime="2022-12-30T16:00:00.000Z">December 30, 2022</time> */}
                                                                </dd>
                                                            </dl>
                                                            <div className="space-y-5 xl:col-span-3">
                                                                <div className="space-y-6">
                                                                    <div>
                                                                        <h2 className="text-2xl font-bold leading-8 tracking-tight">
                                                                            <a className="text-gray-900 dark:text-gray-100" href={"posts/"+post.slug}> {post.title} </a>
                                                                        </h2>
                                                                        <div className="flex flex-wrap">
                                                                            <a className="mr-3 text-sm font-medium uppercase text-primary-500 hover:text-primary-600 dark:hover:text-primary-400" href="/tags/general">general</a>
                                                                        </div>
                                                                    </div>
                                                                    <div className="prose max-w-none text-gray-500 dark:text-gray-400"> {post.summary} </div>
                                                                </div>
                                                                <div className="text-base font-medium leading-6">
                                                                    <a href={"posts/"+post.slug} className="text-primary-500 hover:text-primary-600 dark:hover:text-primary-400" aria-label="Read &quot;Thoughts on life and death&quot;">Read more →</a>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </article>
                                                </li>
                                            )) ) : ("") 
                                        }
                                    </ul>
                                </div>
                            </main>
                        </div>
                    </div>
                </div>
                <div className="flex flex-col">
                    <Footer />
                </div>
            </>
        );
}

export async function getServerSideProps(context:any) {
    const publicPost = await fetch( process.env.WEB_URL+"/api/public/posts?count=50", { method: 'GET', headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' } });
    const publicPostData = await publicPost.json();

    return {
        props: {
            "publicPosts" : publicPostData && publicPostData.data ? publicPostData.data : []
        }
    }
}